syntax on
color smyck
highlight Pmenu guibg=white guifg=black gui=bold
highlight Comment gui=bold
highlight Normal gui=none
highlight NonText guibg=none

set mouse=a
set wrapscan
set smartcase

set splitbelow
set splitright

set termguicolors

filetype plugin indent on
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set incsearch ignorecase smartcase hlsearch
set ruler laststatus=2 showcmd showmode
set nolist
set wrap breakindent
set encoding=utf-8
set number
set title

" Change leader key from "\" to ";"
let mapleader=";"

" improved keyboard navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Disable .swp already exists warning
set shortmess+=A

" Markdown

au FileType markdown setlocal spell

" Programming languages

" Always draw the signcolumn.
set signcolumn=yes

" Display function signatures in echo area
set cmdheight=2
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = 'signature'


" Python

autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Automatically start language servers.
let g:LanguageClient_autoStart = 1
let g:LanguageClient_signColumnAlwaysOn = 1
" let g:LanguageClient_loggingLevel = 'DEBUG'

let g:LanguageClient_serverCommands = {
\ 'python': ['pyls']
\ }

function SetLSPShortcuts()
  nnoremap <F5> :call LanguageClient_contextMenu()<CR>
  nnoremap <silent> gh :call LanguageClient_textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
  nnoremap <silent> gr :call LanguageClient_textDocument_references()<CR>
  nnoremap <silent> gs :call LanguageClient_textDocument_documentSymbol()<CR>
  nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
  nnoremap <silent> gf :call LanguageClient_textDocument_formatting()<CR>

endfunction()

augroup LSP
  autocmd!
  autocmd FileType python call SetLSPShortcuts()
augroup END

" ale options
let g:ale_echo_cursor = '1'

let g:ale_python_flake8_options = '--ignore=E129,E501,E302,E265,E241,E305,E402,W503'
let g:ale_python_pylint_options = '-j 0 --max-line-length=79'
let g:ale_list_window_size = 4
let g:ale_sign_column_always = 0
let g:ale_open_list = 0
let g:ale_keep_list_window_open = '0'
let g:ale_lint_on_enter = '0'
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_save = '1'

let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'

let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_linters = {'python': ['flake8', 'mypy', 'pydocstyle', 'pyls']}
let g:ale_fixers = {'python': ['remove_trailing_lines', 'isort', 'yapf']}
"let g:airline#extensions#ale#enabled = 1

:au BufEnter * if &buftype == 'terminal' | :startinsert | endif
:tnoremap <Esc> <C-\><C-n>

tnoremap <C-w>h <C-\><C-n><C-w>h
tnoremap <C-w>j <C-\><C-n><C-w>j
tnoremap <C-w>k <C-\><C-n><C-w>k
tnoremap <C-w>l <C-\><C-n><C-w>l

" Golang

autocmd Filetype go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

let g:go_auto_sameids = 1
let g:go_fmt_command = "goimports"
let g:go_goimports_bin = "goimports -tabwidth=4"
let g:go_auto_type_info = 1

let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
