# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

##
## prompt
##

#PS1='\[\033[01;34m\]\w\[\033[00m\]\$ '
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\]\n\$ "

# No locking on Ctrl-S
stty -ixon

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


##
## history: http://mywiki.wooledge.org/BashFAQ/088
##

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Big history
HISTFILESIZE=10000
HISTSIZE=10000

# history -a causes an immediate write of all new history lines
# (instead of upon shell exit)
PROMPT_COMMAND="history -a"

# histappend which causes all new history lines to be appended, and ensures
# that multiple logins do not overwrite each other's history
shopt -s histappend

##
## completion
##

# Copied over from the default Ubuntu config
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [ -d ~/.nix-profile/etc/bash_completion.d ]; then
  for bcfile in ~/.nix-profile/etc/bash_completion.d/* ; do
    . $bcfile
  done
fi

if [ -d ~/.nix-profile/share/bash-completion/completions ]; then
  for bcfile in ~/.nix-profile/share/bash-completion/completions/* ; do
    . $bcfile
  done
fi

##
## fzf
##

# FIXME(timaa2k): implicit dependency fzf-share
if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/completion.bash"
fi

if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
fi

##
## Aliases
##

alias ..="cd ..";
alias ls="exa -F --group-directories-first"
alias ll="exa -lFBgm --group-directories-first"
alias la="ll -a";
alias wd="j";
alias :e="vim"

alias xo="xdg-open"
alias tmp='cd $(mktemp -d)'

alias gti="git"
alias gd="git diff"
alias git-delete-merged="git branch --merged | egrep -v '(^\*|master|dev)' | xargs git branch -d"

function t {
    if [ -n "$1" ]; then
        cd "$1"
    fi
    tmux -2 new-session \; split-window -h \; attach
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
