# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# No locking on Ctrl-S
stty -ixon

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


##
## history: http://mywiki.wooledge.org/BashFAQ/088
##

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Big history
HISTFILESIZE=10000
HISTSIZE=10000

# histappend which causes all new history lines to be appended, and ensures
# that multiple logins do not overwrite each other's history
shopt -s histappend

##
## completion
##

# Copied over from the default Ubuntu config
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [ -d ~/.nix-profile/etc/bash_completion.d ]; then
  for bcfile in ~/.nix-profile/etc/bash_completion.d/* ; do
    . $bcfile
  done
fi

if [ -d ~/.nix-profile/share/bash-completion/completions ]; then
  for bcfile in ~/.nix-profile/share/bash-completion/completions/* ; do
    . $bcfile
  done
fi

##
## fzf
##

# FIXME(timaa2k): implicit dependency fzf-share
if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/completion.bash"
fi

if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
fi

##
## Aliases
##

alias ..="cd ..";
alias ls="exa -F --group-directories-first"
alias ll="exa -lFBgm --group-directories-first"
alias la="ll -a";
alias wd="j";
alias :e="vim"

alias xo="xdg-open"
alias tmp='cd $(mktemp -d)'

alias gti="git"
alias gd="git diff"
alias git-delete-merged="git branch --merged | egrep -v '(^\*|master|dev)' | xargs git branch -d"

function t {
    if [ -n "$1" ]; then
        cd "$1"
    fi
    tmux -2 new-session \; split-window -h \; attach
}

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


##
## prompt
##

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PROMPT_COMMAND=__prompt_command

__prompt_command() {
    local Exit="$?"
    PS1=""

    local RCol='\[\e[0m\]'

    local Red='\[\e[0;31m\]'
    local Gre='\[\e[0;32m\]'
    local BYel='\[\e[1;33m\]'
    local BBlu='\[\e[1;34m\]'

    PS1+="\u@\h ${BBlu}\w${RCol}${Gre}$(parse_git_branch)${RCol}\n"

    if [ $Exit != 0 ]; then
        PS1+="${Red}[${Exit}]"
    fi

    PS1+="${RCol}\$ "

    history -a
}
